/**
 * SMTP mail sender using Nodemailer
 * Environment variables required:
 * - SMTP_HOST
 * - SMTP_PORT
 * - SMTP_USER
 * - SMTP_PASS
 * - SMTP_FROM
 */

import { createTransport } from 'nodemailer';
import nodemailer from 'nodemailer';

/**
 * Send an email using SMTP settings from environment variables.
 * @param {string} to - Receiver email address (single or comma-separated)
 * @param {string} html - HTML content/template for the email body
 * @param {string} [subject] - Email subject (optional)
 * @returns {Promise<object>} nodemailer send result
 */
async function sendMail(to, html, subject = 'Notification') {
	if (!to) throw new Error('Missing `to` address for sendMail');
	if (!html) throw new Error('Missing `html` content for sendMail');

		const user = process.env.SMTP_USER;
		const pass = process.env.SMTP_PASS;
		const from = process.env.SMTP_FROM || user;

		if (!user || !pass) {
			throw new Error('SMTP configuration missing. Please set SMTP_USER and SMTP_PASS');
		}

		// Use Gmail service with the same email and password
        const transporter = nodemailer.createTransport({
            service: "gmail",
            auth: {
                user: process.env.APP_EMAIL, // The email that sends the mail
                pass: process.env.APP_PASSWORD, // The App Password generated by Google
            },
        });

	const mailOptions = {
		from,
		to,
		subject,
		html,
	};

	const info = await transporter.sendMail(mailOptions);
	return info;
}

export default sendMail;

